<?php

namespace App\Enums;

enum AuditActionEnum: string
{
    case REGISTERED = 'REGISTERED';
    case VERIFICATION_EMAIL_SENT = 'VERIFICATION_EMAIL_SENT';
    case EMAIL_VERIFIED = 'EMAIL_VERIFIED';
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case TOKEN_REFRESHED = 'TOKEN_REFRESHED';
    case OTP_SENT = 'OTP_SENT';
    case OTP_VERIFIED = 'OTP_VERIFIED';
    case OTP_FAILED = 'OTP_FAILED';
    case PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED';
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case PROFILE_UPDATED = 'PROFILE_UPDATED';
    case PAYMENT_METHOD_DELETED = 'PAYMENT_METHOD_DELETED';
    case PAYMENT_METHOD_DEFAULT_SET = 'PAYMENT_METHOD_DEFAULT_SET';

    case CONSTITUENT_INVITED = 'CONSTITUENT_INVITED';
    case CONSTITUENT_UPDATED = 'CONSTITUENT_UPDATED';
    case CONSTITUENT_ACCESS_REVOKED = 'CONSTITUENT_ACCESS_REVOKED';
    case CONSTITUENT_REACTIVATED = 'CONSTITUENT_REACTIVATED';
    case CONSTITUENT_INVITE_RESENT = 'CONSTITUENT_INVITE_RESENT';
    case CONSTITUENT_PLEDGE_REMINDER_SENT = 'CONSTITUENT_PLEDGE_REMINDER_SENT';

    case CAMPAIGN_CREATED = 'CAMPAIGN_CREATED';
    case CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED';
    case CAMPAIGN_ACTIVATED = 'CAMPAIGN_ACTIVATED';
    case CAMPAIGN_PAUSED = 'CAMPAIGN_PAUSED';
    case CAMPAIGN_RESUMED = 'CAMPAIGN_RESUMED';
    case CAMPAIGN_DEACTIVATED = 'CAMPAIGN_DEACTIVATED';
    case CAMPAIGN_COMPLETED = 'CAMPAIGN_COMPLETED';
    case CAMPAIGN_DELETED = 'CAMPAIGN_DELETED';
    case CAMPAIGN_REPORT_GENERATED = 'CAMPAIGN_REPORT_GENERATED';
    case CAMPAIGN_INSTITUTION_ADDED = 'CAMPAIGN_INSTITUTION_ADDED';
    case CAMPAIGN_INSTITUTION_UPDATED = 'CAMPAIGN_INSTITUTION_UPDATED';
    case CAMPAIGN_INSTITUTION_REMOVED = 'CAMPAIGN_INSTITUTION_REMOVED';
    case INSTITUTION_CREATED = 'INSTITUTION_CREATED';
    case BANK_ACCOUNT_CREATED = 'BANK_ACCOUNT_CREATED';

    case PLEDGE_CREATED = 'PLEDGE_CREATED';
    case PLEDGE_CANCELLED = 'PLEDGE_CANCELLED';
    case PLEDGE_COMPLETED = 'PLEDGE_COMPLETED';
    case DONATION_CREATED = 'DONATION_CREATED';
    case DONATION_COMPLETED = 'DONATION_COMPLETED';
    case DONATION_PAUSED = 'DONATION_PAUSED';
    case DONATION_RESUMED = 'DONATION_RESUMED';
    case DONATION_MODIFIED = 'DONATION_MODIFIED';
    case DONATION_CANCELLED = 'DONATION_CANCELLED';
    case PAYMENT_INITIATED = 'PAYMENT_INITIATED';
    case PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED';
    case PAYMENT_FAILED = 'PAYMENT_FAILED';

    case EVENT_REGISTRATION_CREATED = 'EVENT_REGISTRATION_CREATED';
    case EVENT_REGISTRATION_COMPLETED = 'EVENT_REGISTRATION_COMPLETED';
    case EVENT_WAITLISTED = 'EVENT_WAITLISTED';

    case EVENT_CREATED = 'EVENT_CREATED';
    case EVENT_UPDATED = 'EVENT_UPDATED';
    case EVENT_DEACTIVATED = 'EVENT_DEACTIVATED';
    case EVENT_REACTIVATED = 'EVENT_REACTIVATED';
    case EVENT_ARCHIVED = 'EVENT_ARCHIVED';
    case EVENT_REPORT_GENERATED = 'EVENT_REPORT_GENERATED';
    case EVENT_REMINDER_SENT = 'EVENT_REMINDER_SENT';

    case MENTOR_APPLICATION_CREATED = 'MENTOR_APPLICATION_CREATED';
    case MENTEE_APPLICATION_CREATED = 'MENTEE_APPLICATION_CREATED';
    case MENTORSHIP_MATCHED = 'MENTORSHIP_MATCHED';
    case MENTOR_LISTING_PAUSED = 'MENTOR_LISTING_PAUSED';
    case MENTOR_LISTING_RESUMED = 'MENTOR_LISTING_RESUMED';
    case MENTORSHIP_REVIEW_CREATED = 'MENTORSHIP_REVIEW_CREATED';
    case MENTOR_APPLICATION_APPROVED = 'MENTOR_APPLICATION_APPROVED';
    case MENTOR_APPLICATION_REJECTED = 'MENTOR_APPLICATION_REJECTED';
    case MENTOR_SUSPENDED = 'MENTOR_SUSPENDED';
    case MENTOR_REACTIVATED = 'MENTOR_REACTIVATED';
    case MENTORSHIP_MATCHED_MANUALLY = 'MENTORSHIP_MATCHED_MANUALLY';

    case BULK_EMAIL_CREATED = 'BULK_EMAIL_CREATED';
    case BULK_EMAIL_SENT = 'BULK_EMAIL_SENT';
    case BULK_EMAIL_DELETED = 'BULK_EMAIL_DELETED';
    case BULK_EMAIL_SET_ACTIVE = 'BULK_EMAIL_SET_ACTIVE';

    case ADMIN_CREATED = 'ADMIN_CREATED';
    case ADMIN_UPDATED = 'ADMIN_UPDATED';
    case ADMIN_STATUS_TOGGLED = 'ADMIN_STATUS_TOGGLED';
    case ADMIN_INVITE_LINK_RESENT = 'ADMIN_INVITE_LINK_RESENT';
    case ADMIN_DELETED = 'ADMIN_DELETED';
    case ROLE_CREATED = 'ROLE_CREATED';
    case ROLE_UPDATED = 'ROLE_UPDATED';
    case ROLE_STATUS_TOGGLED = 'ROLE_STATUS_TOGGLED';
    case ROLE_DELETED = 'ROLE_DELETED';

    case NETWORKING_CHANNEL_CREATED = 'NETWORKING_CHANNEL_CREATED';
    case NETWORKING_CHANNEL_UPDATED = 'NETWORKING_CHANNEL_UPDATED';
    case NETWORKING_CHANNEL_LOCKED = 'NETWORKING_CHANNEL_LOCKED';
    case NETWORKING_CHANNEL_UNLOCKED = 'NETWORKING_CHANNEL_UNLOCKED';
    case NETWORKING_CHANNEL_DELETED = 'NETWORKING_CHANNEL_DELETED';
    case NETWORKING_CHANNEL_MEMBER_ADDED = 'NETWORKING_CHANNEL_MEMBER_ADDED';
    case NETWORKING_CHANNEL_MEMBER_REMOVED = 'NETWORKING_CHANNEL_MEMBER_REMOVED';

    case PROSPECT_CREATED = 'PROSPECT_CREATED';
    case PROSPECT_UPDATED = 'PROSPECT_UPDATED';
    case PROSPECT_STAGE_CHANGED = 'PROSPECT_STAGE_CHANGED';
    case PROSPECT_CALL_LOGGED = 'PROSPECT_CALL_LOGGED';
    case PROSPECT_INVITE_SENT = 'PROSPECT_INVITE_SENT';
    case PROSPECT_PROPOSAL_CREATED = 'PROSPECT_PROPOSAL_CREATED';
    case PROSPECT_PROPOSAL_UPDATED = 'PROSPECT_PROPOSAL_UPDATED';
    case PROSPECT_PROPOSAL_DUPLICATED = 'PROSPECT_PROPOSAL_DUPLICATED';
    case PROSPECT_PROPOSAL_DELETED = 'PROSPECT_PROPOSAL_DELETED';
    case PROSPECT_PROPOSAL_SENT = 'PROSPECT_PROPOSAL_SENT';
    case PROSPECT_PROPOSAL_RESENT = 'PROSPECT_PROPOSAL_RESENT';
    case PROSPECT_PROPOSAL_COLLABORATOR_INVITED = 'PROSPECT_PROPOSAL_COLLABORATOR_INVITED';
    case PROSPECT_MESSAGE_SENT = 'PROSPECT_MESSAGE_SENT';

    case MAIL_CREATED = 'MAIL_CREATED';
    case MAIL_UPDATED = 'MAIL_UPDATED';
    case MAIL_DELETED = 'MAIL_DELETED';
    case MAIL_SENT = 'MAIL_SENT';
    case MAIL_RESENT = 'MAIL_RESENT';

    case COMMUNICATION_CALL_LOGGED = 'COMMUNICATION_CALL_LOGGED';

    case COMMUNICATION_TASK_CREATED = 'COMMUNICATION_TASK_CREATED';
    case COMMUNICATION_TASK_UPDATED = 'COMMUNICATION_TASK_UPDATED';
    case COMMUNICATION_TASK_DELETED = 'COMMUNICATION_TASK_DELETED';
    case COMMUNICATION_TASK_MARKED_DONE = 'COMMUNICATION_TASK_MARKED_DONE';
    case COMMUNICATION_TASK_RECURRENCE_PAUSED = 'COMMUNICATION_TASK_RECURRENCE_PAUSED';
    case COMMUNICATION_TASK_RECURRENCE_RESUMED = 'COMMUNICATION_TASK_RECURRENCE_RESUMED';
    case COMMUNICATION_TASK_RECURRENCE_DISABLED = 'COMMUNICATION_TASK_RECURRENCE_DISABLED';
    case COMMUNICATION_TASK_NOTE_ADDED = 'COMMUNICATION_TASK_NOTE_ADDED';

    /**
     * @return list<string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }
}
