<?php

namespace App\Enums;

enum AuditActionEnum: string
{
    case REGISTERED = 'REGISTERED';
    case VERIFICATION_EMAIL_SENT = 'VERIFICATION_EMAIL_SENT';
    case EMAIL_VERIFIED = 'EMAIL_VERIFIED';
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case TOKEN_REFRESHED = 'TOKEN_REFRESHED';
    case OTP_SENT = 'OTP_SENT';
    case OTP_VERIFIED = 'OTP_VERIFIED';
    case OTP_FAILED = 'OTP_FAILED';
    case PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED';
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case PROFILE_UPDATED = 'PROFILE_UPDATED';
    case PAYMENT_METHOD_DELETED = 'PAYMENT_METHOD_DELETED';
    case PAYMENT_METHOD_DEFAULT_SET = 'PAYMENT_METHOD_DEFAULT_SET';

    case CAMPAIGN_CREATED = 'CAMPAIGN_CREATED';
    case CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED';
    case CAMPAIGN_ACTIVATED = 'CAMPAIGN_ACTIVATED';
    case CAMPAIGN_PAUSED = 'CAMPAIGN_PAUSED';
    case CAMPAIGN_RESUMED = 'CAMPAIGN_RESUMED';
    case CAMPAIGN_DEACTIVATED = 'CAMPAIGN_DEACTIVATED';
    case CAMPAIGN_COMPLETED = 'CAMPAIGN_COMPLETED';
    case CAMPAIGN_DELETED = 'CAMPAIGN_DELETED';
    case CAMPAIGN_REPORT_GENERATED = 'CAMPAIGN_REPORT_GENERATED';
    case CAMPAIGN_INSTITUTION_ADDED = 'CAMPAIGN_INSTITUTION_ADDED';
    case CAMPAIGN_INSTITUTION_UPDATED = 'CAMPAIGN_INSTITUTION_UPDATED';
    case CAMPAIGN_INSTITUTION_REMOVED = 'CAMPAIGN_INSTITUTION_REMOVED';
    case INSTITUTION_CREATED = 'INSTITUTION_CREATED';
    case BANK_ACCOUNT_CREATED = 'BANK_ACCOUNT_CREATED';

    case PLEDGE_CREATED = 'PLEDGE_CREATED';
    case PLEDGE_CANCELLED = 'PLEDGE_CANCELLED';
    case PLEDGE_COMPLETED = 'PLEDGE_COMPLETED';
    case DONATION_CREATED = 'DONATION_CREATED';
    case DONATION_COMPLETED = 'DONATION_COMPLETED';
    case DONATION_PAUSED = 'DONATION_PAUSED';
    case DONATION_RESUMED = 'DONATION_RESUMED';
    case DONATION_MODIFIED = 'DONATION_MODIFIED';
    case DONATION_CANCELLED = 'DONATION_CANCELLED';
    case PAYMENT_INITIATED = 'PAYMENT_INITIATED';
    case PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED';
    case PAYMENT_FAILED = 'PAYMENT_FAILED';

    case EVENT_REGISTRATION_CREATED = 'EVENT_REGISTRATION_CREATED';
    case EVENT_REGISTRATION_COMPLETED = 'EVENT_REGISTRATION_COMPLETED';

    case MENTOR_APPLICATION_CREATED = 'MENTOR_APPLICATION_CREATED';
    case MENTEE_APPLICATION_CREATED = 'MENTEE_APPLICATION_CREATED';
    case MENTORSHIP_MATCHED = 'MENTORSHIP_MATCHED';
    case MENTOR_LISTING_PAUSED = 'MENTOR_LISTING_PAUSED';
    case MENTOR_LISTING_RESUMED = 'MENTOR_LISTING_RESUMED';
    case MENTORSHIP_REVIEW_CREATED = 'MENTORSHIP_REVIEW_CREATED';

    case BULK_EMAIL_CREATED = 'BULK_EMAIL_CREATED';
    case BULK_EMAIL_SENT = 'BULK_EMAIL_SENT';
    case BULK_EMAIL_DELETED = 'BULK_EMAIL_DELETED';
    case BULK_EMAIL_SET_ACTIVE = 'BULK_EMAIL_SET_ACTIVE';

    case ADMIN_CREATED = 'ADMIN_CREATED';
    case ADMIN_UPDATED = 'ADMIN_UPDATED';
    case ADMIN_STATUS_TOGGLED = 'ADMIN_STATUS_TOGGLED';
    case ADMIN_INVITE_LINK_RESENT = 'ADMIN_INVITE_LINK_RESENT';
    case ADMIN_DELETED = 'ADMIN_DELETED';
    case ROLE_CREATED = 'ROLE_CREATED';
    case ROLE_UPDATED = 'ROLE_UPDATED';
    case ROLE_STATUS_TOGGLED = 'ROLE_STATUS_TOGGLED';
    case ROLE_DELETED = 'ROLE_DELETED';

    case NETWORKING_CHANNEL_CREATED = 'NETWORKING_CHANNEL_CREATED';
    case NETWORKING_CHANNEL_UPDATED = 'NETWORKING_CHANNEL_UPDATED';
    case NETWORKING_CHANNEL_LOCKED = 'NETWORKING_CHANNEL_LOCKED';
    case NETWORKING_CHANNEL_UNLOCKED = 'NETWORKING_CHANNEL_UNLOCKED';
    case NETWORKING_CHANNEL_DELETED = 'NETWORKING_CHANNEL_DELETED';
    case NETWORKING_CHANNEL_MEMBER_ADDED = 'NETWORKING_CHANNEL_MEMBER_ADDED';
    case NETWORKING_CHANNEL_MEMBER_REMOVED = 'NETWORKING_CHANNEL_MEMBER_REMOVED';

    /**
     * @return list<string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }
}
