name: 🚀 Deploy update on merge to main
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.jkp.mje.mybluehost.me
          username: developer@nhef-advance-impact-api.sbscuk.co.uk
          password: Y[vN1f8I{w9f